server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopee_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: admin
      password: admin@123

    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  app:
    jwtSecret: JwNaAabf8jVEPAD+cpoSgYLukges1KRWEKnDF+XY5QfGO55I9lCzxyqtUyLw5G8q
    jwtExpiration: 5000000
    jwtRefreshExpirationMs: 86400000
    jwtCookieName : shopee_jwt
    jwtRefreshCookieName: shopee_jwt_refresh
  web:
    resources:
      static-locations:
        - file:///C:/Users/Lenovo/Downloads/shopee-clone-be-develop/images/
project:
  image: "images/"
